version: "3.8"

services:
  python-app:
    build:
      context: ../app_python
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ../:/app_python
      - ./app-logs:/app_python/logs
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - loki
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.1
    volumes:
      - ./loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
      - ./app-logs:/app_python/logs
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  grafana-data:
  app-logs:
